image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
    COMMON_FLAGS: -p:PublishTrimmed=false -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    OUTPUT_DIR_WIN64: bin/Release/net6.0/win-x64/publish
    OUTPUT_DIR_LINUX64: bin/Release/net6.0/linux-x64/publish
    GIT_SUBMODULE_STRATEGY: recursive
    OUTPUT_FILE_PREFIX: 2009scape-launcher-$CI_COMMIT_SHORT_SHA

stages:
    - build_all
    - pack_linux_no_rt
    - pack_linux_sc
    - pack_windows_no_rt
    - pack_windows_sc

before_script:
    - dotnet restore
    - cd Saradomin

build_all:
    stage: build_all
    script:
        - dotnet publish --runtime linux-x64 --no-self-contained -c Release $COMMON_FLAGS
        - mv $OUTPUT_DIR_LINUX64/Saradomin $OUTPUT_DIR_LINUX64/$OUTPUT_FILE_PREFIX-no_rt
        - dotnet publish --runtime linux-x64 --self-contained -c Release $COMMON_FLAGS
        - mv $OUTPUT_DIR_LINUX64/Saradomin $OUTPUT_DIR_LINUX64/$OUTPUT_FILE_PREFIX-sc
        - dotnet publish --runtime win-x64 --no-self-contained -c Release $COMMON_FLAGS
        - mv $OUTPUT_DIR_WIN64/Saradomin.exe $OUTPUT_DIR_WIN64/$OUTPUT_FILE_PREFIX-no_rt.exe
        - dotnet publish --runtime win-x64 --self-contained -c Release $COMMON_FLAGS
        - mv $OUTPUT_DIR_WIN64/Saradomin.exe $OUTPUT_DIR_WIN64/$OUTPUT_FILE_PREFIX-sc.exe

pack_linux_no_rt:
    stage: pack_linux_no_rt
    script:
        - echo "Packing no-runtime build for Linux x64..."
    artifacts:
        name: "Linux x64 (no embedded runtime)"
        paths:
            - Saradomin/$OUTPUT_DIR_LINUX64/$OUTPUT_FILE_PREFIX-no_rt

pack_linux_sc:
    stage: pack_linux_sc
    script:
        - echo "Packing self-contained build for Linux x64..."
    artifacts:
        name: "Linux x64 (self-contained)"
        paths:
            - Saradomin/$OUTPUT_DIR_LINUX64/$OUTPUT_FILE_PREFIX-sc

pack_windows_no_rt:
    stage: pack_windows_no_rt
    script:
        - echo "Packing no-runtime build for Windows x64..."
    artifacts:
        name: "Windows x64 (no embedded runtime)"
        paths:
            - Saradomin/$OUTPUT_DIR_WIN64/$OUTPUT_FILE_PREFIX-no_rt.exe

pack_windows_sc:
    stage: pack_windows_sc
    script:
        - echo "Packing self-contained build for Windows x64..."
    artifacts:
        name: "Windows x64 (self-contained)"
        paths:
            - Saradomin/$OUTPUT_DIR_WIN64/$OUTPUT_FILE_PREFIX-sc.exe
