name: Create Artifacts
run-name: ${{ github.actor }} is creating Artifacts
on:
  - push
  - workflow_dispatch

env:
  DEFAULT_BRANCH: "refs/heads/master"
  COMMON_FLAGS: -p:PublishTrimmed=false -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
  OUTPUT_FILE_PREFIX: 2009scape-launcher
  PUBLISH_DIR_LINUX64: bin/Release/net6.0/linux-x64/publish
  PUBLISH_DIR_WIN64: bin/Release/net6.0/win-x64/publish

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["8.0.x"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      
      - name: Add Required Folders
        run: |
          mkdir -p output/linux
          mkdir -p output/windows

      - name: Publish Linux Files
        working-directory: ./Saradomin
        run: |
          mkdir -p ../output
          dotnet publish --runtime linux-x64 --self-contained -c Release $COMMON_FLAGS
          mv -v $PUBLISH_DIR_LINUX64/Saradomin ../output/linux/${{ env.OUTPUT_FILE_PREFIX }}-sc

      - name: Upload Linux Files
        uses: actions/upload-artifact@v3
        with:
          name: Linux Launcher
          path: output/linux
          retention-days: 5

      - name: Publish Windows Files
        working-directory: ./Saradomin
        run: |
          dotnet publish --runtime win-x64 --self-contained -c Release $COMMON_FLAGS
          mv -v $PUBLISH_DIR_WIN64/Saradomin.exe ../output/windows/$OUTPUT_FILE_PREFIX-sc.exe

      - name: Upload Windows Files
        uses: actions/upload-artifact@v3
        with:
          name: Windows Launcher
          path: output/windows
          retention-days: 5
